# Crime_Complaints_And_Arrests_NYC_Data_Project

### 1. What crimes are most likely to lead to an arrest (reframe)
### 2. Which Percentage of gender gets arrested more
### 3. Which Percentage of race gets arrested more
### 4. Which neighborhoods crime will lead to an arrest (reframe)
### 5. What years had more complaints happens

In [2]:
import pandas as pd 
import seaborn as sns
import geopandas as gpd
import numpy as np
import matplotlib.pyplot as plt

In [8]:
url = "https://data.cityofnewyork.us/resource/qgea-i56i.json?$limit=60000"

complaints = pd.read_json(url)
complaints

,cmplnt_num,cmplnt_fr_dt,cmplnt_fr_tm,cmplnt_to_dt,cmplnt_to_tm,addr_pct_cd,rpt_dt,ky_cd,ofns_desc,pd_cd,...,station_name,vic_age_group,vic_race,vic_sex,:@computed_region_efsh_h5xi,:@computed_region_f5dn_yrer,:@computed_region_yeji_bk3q,:@computed_region_92fq_4b7q,:@computed_region_sbqj_enih,transit_district
0,318194660,2025-10-04T00:00:00.000,10:00:00,2025-12-25T00:00:00.000,12:00:00,105,2025-12-31T00:00:00.000,109,GRAND LARCENY,403.0,...,(null),65+,WHITE,M,24336.0,63.0,3.0,16.0,63.0,NaN
1,318202701,2025-12-31T00:00:00.000,17:40:00,2025-12-31T00:00:00.000,17:49:00,67,2025-12-31T00:00:00.000,578,HARRASSMENT 2,638.0,...,(null),45-64,BLACK,F,16866.0,61.0,2.0,26.0,40.0,NaN
2,318170929,2025-12-31T00:00:00.000,01:00:00,2025-12-31T00:00:00.000,01:08:00,107,2025-12-31T00:00:00.000,126,MISCELLANEOUS PENAL LAW,760.0,...,PARSONS BLVD.,UNKNOWN,UNKNOWN,E,24340.0,41.0,3.0,24.0,61.0,20.0
3,318205004,2025-12-30T00:00:00.000,17:30:00,2025-12-31T00:00:00.000,06:00:00,75,2025-12-31T00:00:00.000,110,GRAND LARCENY OF MOTOR VEHICLE,455.0,...,(null),25-44,WHITE HISPANIC,M,17214.0,45.0,2.0,37.0,47.0,NaN
4,318230186,2025-12-31T00:00:00.000,22:45:00,2025-12-31T00:00:00.000,22:50:00,107,2025-12-31T00:00:00.000,361,OFF. AGNST PUB ORD SENSBLTY &,661.0,...,(null),UNKNOWN,UNKNOWN,E,14507.0,25.0,3.0,24.0,65.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
59995,316392866,2025-11-19T00:00:00.000,21:00:00,2025-11-20T00:00:00.000,08:30:00,108,2025-11-20T00:00:00.000,342,PETIT LARCENY OF MOTOR VEHICLE,350.0,...,(null),25-44,WHITE HISPANIC,M,14787.0,53.0,3.0,33.0,66.0,NaN
59996,316452450,2025-11-13T00:00:00.000,11:54:00,2025-11-13T00:00:00.000,12:20:00,110,2025-11-20T00:00:00.000,341,PETIT LARCENY,333.0,...,(null),UNKNOWN,UNKNOWN,D,14784.0,66.0,3.0,5.0,68.0,NaN
59997,316719209,2025-11-19T00:00:00.000,15:40:00,2025-11-19T00:00:00.000,16:00:00,14,2025-11-20T00:00:00.000,361,OFF. AGNST PUB ORD SENSBLTY &,639.0,...,(null),25-44,WHITE,F,12080.0,12.0,4.0,10.0,8.0,NaN
59998,316382604,2025-11-20T00:00:00.000,05:30:00,2025-11-20T00:00:00.000,05:40:00,44,2025-11-20T00:00:00.000,578,HARRASSMENT 2,638.0,...,(null),25-44,WHITE,F,10930.0,50.0,5.0,42.0,27.0,NaN
59999,317306108,2025-07-17T00:00:00.000,04:30:00,2025-11-03T00:00:00.000,10:00:00,42,2025-11-20T00:00:00.000,341,PETIT LARCENY,352.0,...,(null),65+,WHITE HISPANIC,F,10937.0,34.0,5.0,43.0,25.0,NaN

In [12]:
arrest = pd.read_json('https://data.cityofnewyork.us/api/v3/views/uip8-fykc/query.json?$limit=60000')
arrest

,:id,:version,:created_at,:updated_at,arrest_key,arrest_date,pd_cd,pd_desc,ky_cd,ofns_desc,...,x_coord_cd,y_coord_cd,latitude,longitude,geocoded_column,:@computed_region_f5dn_yrer,:@computed_region_yeji_bk3q,:@computed_region_92fq_4b7q,:@computed_region_sbqj_enih,:@computed_region_efsh_h5xi
0,row-4sgt~gidr-fbmz,rv-n7bv~xc3v_gf8g,2026-04-28 15:55:10.985000+00:00,2026-04-28 15:55:25.073000+00:00,318451126,2026-01-06T00:00:00.000,105.0,STRANGULATION 1ST,106.0,FELONY ASSAULT,...,1020232,210719,40.744989,-73.870145,"{'type': 'Point', 'coordinates': [-73.870145, ...",66.0,3.0,21.0,68.0,14784.0
1,row-r7z4~k24s.rsj7,rv-yz8w_k6bt~ctwb,2026-04-28 15:55:10.985000+00:00,2026-04-28 15:55:25.073000+00:00,318308486,2026-01-03T00:00:00.000,203.0,"TRESPASS 3, CRIMINAL",352.0,CRIMINAL TRESPASS,...,1003358,182945,40.668798,-73.931120,"{'type': 'Point', 'coordinates': [-73.93112014...",17.0,2.0,48.0,44.0,17615.0
2,row-akub-3fyj_ddmr,rv-ndug~bf2c.9p5m,2026-04-28 15:55:10.985000+00:00,2026-04-28 15:55:25.073000+00:00,318550123,2026-01-08T00:00:00.000,105.0,STRANGULATION 1ST,106.0,FELONY ASSAULT,...,1011780,246837,40.844152,-73.900500,"{'type': 'Point', 'coordinates': [-73.9005, 40...",35.0,5.0,22.0,31.0,10935.0
3,row-bz7k~8esg_9x95,rv-v427-vdvd.pifg,2026-04-28 15:55:10.985000+00:00,2026-04-28 15:55:25.073000+00:00,318580867,2026-01-07T00:00:00.000,397.0,"ROBBERY,OPEN AREA UNCLASSIFIED",105.0,ROBBERY,...,999788,233328,40.807102,-73.943874,"{'type': 'Point', 'coordinates': [-73.943874, ...",18.0,4.0,36.0,18.0,12424.0
4,row-v8dg.usth~xk7y,rv-mb7c_krpw_5wdc,2026-04-28 15:55:10.985000+00:00,2026-04-28 15:55:25.073000+00:00,318684449,2026-01-10T00:00:00.000,397.0,"ROBBERY,OPEN AREA UNCLASSIFIED",105.0,ROBBERY,...,1031351,254245,40.864401,-73.829711,"{'type': 'Point', 'coordinates': [-73.829711, ...",43.0,5.0,2.0,28.0,12344.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69300,row-nkgw.hq6h.i3fm,rv-riht_p49s-hanb,2026-04-28 15:55:10.985000+00:00,2026-04-28 15:55:33.162000+00:00,322107704,2026-03-20T00:00:00.000,101.0,ASSAULT 3,344.0,ASSAULT 3 & RELATED OFFENSES,...,997877,181865,40.665852,-73.950879,"{'type': 'Point', 'coordinates': [-73.950879, ...",17.0,2.0,48.0,44.0,13509.0
69301,row-p2sv_j7aj.2vpf,rv-557k_izxd-r6mm,2026-04-28 15:55:10.985000+00:00,2026-04-28 15:55:33.162000+00:00,321792737,2026-03-13T00:00:00.000,244.0,"BURGLARY,UNCLASSIFIED,UNKNOWN",107.0,BURGLARY,...,1006537,244511,40.837782,-73.919457,"{'type': 'Point', 'coordinates': [-73.919457, ...",50.0,5.0,42.0,27.0,10930.0
69302,row-aqx5~8sx3~36bp,rv-j6vy-nxwi~km98,2026-04-28 15:55:10.985000+00:00,2026-04-28 15:55:33.162000+00:00,321311225,2026-03-05T00:00:00.000,259.0,"CRIMINAL MISCHIEF,UNCLASSIFIED 4",351.0,CRIMINAL MISCHIEF & RELATED OF,...,995270,235835,40.813992,-73.960190,"{'type': 'Point', 'coordinates': [-73.96019, 4...",37.0,4.0,23.0,17.0,12424.0
69303,row-sva7-qhbp-chkw,rv-euuk_ymbw.amxx,2026-04-28 15:55:10.985000+00:00,2026-04-28 15:55:33.162000+00:00,322521247,2026-03-27T00:00:00.000,764.0,BAIL JUMPING 1 & 2,126.0,MISCELLANEOUS PENAL LAW,...,1032501,198800,40.712215,-73.825953,"{'type': 'Point', 'coordinates': [-73.825953, ...",46.0,3.0,28.0,60.0,24011.0
69304,row-jhgv.q4p6-aj6d,rv-sjke.8t83~9qs7,2026-04-28 15:55:10.985000+00:00,2026-04-28 15:55:33.162000+00:00,321602181,2026-03-10T00:00:00.000,744.0,BAIL JUMPING 3,359.0,OFFENSES AGAINST PUBLIC ADMINI,...,1032501,198800,40.712215,-73.825953,"{'type': 'Point', 'coordinates': [-73.825953, ...",46.0,3.0,28.0,60.0,24011.0

In [15]:
arrest.dtypes

:id                                            str
:version                                       str
:created_at                    datetime64[us, UTC]
:updated_at                    datetime64[us, UTC]
arrest_key                                   int64
arrest_date                                    str
pd_cd                                      float64
pd_desc                                        str
ky_cd                                      float64
ofns_desc                                      str
law_code                                       str
law_cat_cd                                     str
arrest_boro                                    str
arrest_precinct                              int64
jurisdiction_code                            int64
age_group                                      str
perp_sex                                       str
perp_race                                      str
x_coord_cd                                   int64
y_coord_cd                                   int64
latitude                                   float64
longitude                                  float64
geocoded_column                             object
:@computed_region_f5dn_yrer                float64
:@computed_region_yeji_bk3q                float64
:@computed_region_92fq_4b7q                float64
:@computed_region_sbqj_enih                float64
:@computed_region_efsh_h5xi                float64
dtype: object

In [16]:
complaints.dtypes

cmplnt_num                         str
cmplnt_fr_dt                       str
cmplnt_fr_tm                       str
cmplnt_to_dt                       str
cmplnt_to_tm                       str
addr_pct_cd                      int64
rpt_dt                             str
ky_cd                            int64
ofns_desc                          str
pd_cd                          float64
pd_desc                            str
crm_atpt_cptd_cd                   str
law_cat_cd                         str
boro_nm                            str
loc_of_occur_desc                  str
prem_typ_desc                      str
juris_desc                         str
jurisdiction_code                int64
parks_nm                           str
hadevelopt                         str
housing_psa                        str
x_coord_cd                       int64
y_coord_cd                       int64
susp_age_group                     str
susp_race                          str
susp_sex                           str
latitude                       float64
longitude                      float64
lat_lon                         object
patrol_boro                        str
station_name                       str
vic_age_group                      str
vic_race                           str
vic_sex                            str
:@computed_region_efsh_h5xi    float64
:@computed_region_f5dn_yrer    float64
:@computed_region_yeji_bk3q    float64
:@computed_region_92fq_4b7q    float64
:@computed_region_sbqj_enih    float64
transit_district               float64
dtype: object

In [13]:
print(complaints["pd_cd"].nunique())
print(arrest["pd_cd"].nunique())

print(complaints["pd_cd"].value_counts().head(10))
print(arrest["pd_cd"].value_counts().head(10))

310
227
pd_cd
638.0    7039
101.0    4851
333.0    4789
109.0    2216
637.0    2008
922.0    1822
352.0    1719
639.0    1640
198.0    1446
478.0    1196
Name: count, dtype: int64
pd_cd
101.0    7036
339.0    6478
922.0    4602
478.0    3889
109.0    3663
779.0    2966
511.0    2935
397.0    2581
439.0    2023
113.0    1654
Name: count, dtype: int64

In [14]:
complaint_counts = complaints["pd_cd"].value_counts()
arrest_counts = arrest["pd_cd"].value_counts()

estimated_rows = (
    complaint_counts
    .to_frame("complaint_count")
    .join(arrest_counts.to_frame("arrest_count"), how="inner")
)

estimated_rows["merged_rows"] = (
    estimated_rows["complaint_count"] *
    estimated_rows["arrest_count"]
)

print(estimated_rows["merged_rows"].sum())

77300009

In [15]:
estimated_rows.sort_values(
    "merged_rows",
    ascending=False
).head(10)

       complaint_count  arrest_count  merged_rows
pd_cd
101.0             4851          7036     34131636
922.0             1822          4602      8384844
109.0             2216          3663      8117208
339.0              926          6478      5998628
478.0             1196          3889      4651244
511.0              942          2935      2764770
113.0             1193          1654      1973222
639.0             1640          1148      1882720
259.0             1127           975      1098825
439.0              363          2023       734349

In [4]:

nys_data = gpd.read_file("nynta2020_26b/nynta2020.shp")